services:
  myapp:
    image: ${DOCKER_REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: ..
      dockerfile: /Dockerfile
      args:
        - DOCKER_USERNAME=${DOCKER_USERNAME}
        - DOCKER_TOKEN=${DOCKER_TOKEN}
        - SONAR_URL=${SONAR_URL}
        - SONAR_TOKEN=${SONAR_TOKEN}
        - GITHUBLOGIN=${GITHUBLOGIN}
        - GITHUBTOKEN=${GITHUBTOKEN}
        - IMAGE_NAME=${IMAGE_NAME}