services:
  myapp:
    image: ${DOCKER_REPO_NAME:-localhost}/${IMAGE_NAME:-myapp}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${DOCKER_TARGET:-finallibs}
      args:
        - GITHUBACTOR=${GITHUBACTOR}
        - GITHUBTOKEN=${GITHUBTOKEN}
        - APP_MAIN_CLASS=${APP_MAIN_CLASS:-}
    environment:
      - APP_MAIN_CLASS=${APP_MAIN_CLASS:-}
