services:
  myapp:
    image: ${DOCKER_REPO_NAME:-localhost}/${IMAGE_NAME:-myapp}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${DOCKER_TARGET:-finalShadedJarDebian}
      args:
        - GITHUBACTOR=${GITHUBACTOR}
        - GITHUBTOKEN=${GITHUBTOKEN}
        - SONAR_URL=${SONAR_URL}
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - APP_MAIN_CLASS=${APP_MAIN_CLASS:-}
