name: CI Java (Host)

on:
  push:
  workflow_dispatch:

jobs:
    build:
        name: build-sonar-site-upload
        uses: ebpro/gh-actions-shared-java/.github/workflows/ci-shareable-maven.yml@develop
        secrets: inherit
